const fs = require('fs');
const path = require('path');

// Existing profiles
const profilesPath = path.join(__dirname, '../lib/profiles.json');
const existingProfiles = require(profilesPath);

// New data provided by user
const newStudents = [
  {
    id: "thomas-cattarossi",
    name: "Thomas CATTAROSSI DARTIGUELONGUE",
    role: "Full Stack Developer",
    photo: "/students/thomas.png",
    bio: "Full stack developer passionate about Python backend and modern JavaScript frameworks. Agile methodology enthusiast.",
    age: 21,
    dateOfBirth: "2004-05-08",
    placeOfBirth: "Mont-de-Marsan, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Python (API/Backend)", "Next.js / Vue.js", "Scrum / Agile"],
    weaknesses: ["C#", "Database management", "Windev/Webdev"],
    biggestAchievement: "Made a fully fledged and complete chess tournament simulator on Python",
    funFact: "I listen to a ton of music everyday",
  },
  {
    id: "ahmed-dahdouh",
    name: "Ahmed DAHDOUH",
    role: "Software Developer",
    photo: "/students/ahmed.png",
    bio: "Software developer passionate about creating innovative solutions. Always eager to learn new technologies.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Problem Solving", "Teamwork", "Adaptability"],
    weaknesses: ["Public Speaking", "Time Management"],
    biggestAchievement: "Successfully completed multiple challenging projects in M2DWM program",
    funFact: "Coffee enthusiast who codes better with a fresh brew",
  },
  {
    id: "badre-elmourabit",
    name: "Badre EL MOURABIT",
    role: "Software Engineer",
    photo: "/students/badre.png",
    bio: "Experienced software engineer with a passion for building robust applications. Team player with strong technical skills.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Software Architecture", "Code Quality", "Debugging"],
    weaknesses: ["Frontend Design", "Documentation"],
    biggestAchievement: "Developed scalable solutions for complex business problems",
    funFact: "Can debug code while listening to heavy metal music",
  },
  {
    id: "manal-ezzaher",
    name: "Manal EZ-ZAHER",
    role: "Software Developer",
    photo: "/students/manal.jpg",
    bio: "Creative developer with attention to detail. Passionate about clean code and user experience.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Attention to Detail", "Problem Solving", "Learning Agility"],
    weaknesses: ["Backend Architecture", "DevOps"],
    biggestAchievement: "Built responsive applications with excellent user feedback",
    funFact: "Loves solving puzzles and brain teasers in free time",
  },
  {
    id: "medjourney",
    name: "Mehdi GHOULAM",
    role: "Full Stack Developer",
    photo: "/students/medjourney.png",
    bio: "Co-founder of Mindlet 🐙. Full stack developer specializing in TypeScript, React ecosystem, and PHP/Laravel. Passionate about building innovative products.",
    age: 23,
    dateOfBirth: "2002-09-07",
    placeOfBirth: "Mulhouse, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["TypeScript", "React", "React Native", "PHP", "Laravel", "API", "PostgreSQL"],
    weaknesses: ["Python"],
    biggestAchievement: "Co-founder of Mindlet 🐙",
    funFact: "When it works, don't touch it!",
  },
  {
    id: "dorian",
    name: "Dorian LOVICHI",
    role: "Full Stack Developer & DevOps",
    photo: "/students/dorian.jpg",
    bio: "Full-stack developer with DevOps expertise and AI integration skills. Passionate about creating innovative solutions.",
    age: 23,
    dateOfBirth: "2002-05-08",
    placeOfBirth: "Ajaccio, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Full-Stack Development", "DevOps", "AI Integration"],
    weaknesses: ["UI/UX"],
    biggestAchievement: "Create an AI girlfriend",
    funFact: "Number one boucherville fan!",
  },
  {
    id: "anthony-marchiselli",
    name: "Anthony MARCHISELLI",
    role: "Software Developer",
    photo: "/students/anthony.png",
    bio: "Dedicated software developer with a passion for learning and implementing new technologies.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Coding", "Analytical Thinking", "Team Collaboration"],
    weaknesses: ["Advanced Algorithms", "System Design"],
    biggestAchievement: "Completed several successful projects in the M2DWM program",
    funFact: "Enjoys gaming and coding challenges in equal measure",
  },
  {
    id: "antocreadev",
    name: "Anthony Pierre Philippe MENGHI",
    role: "Full Stack Developer & AI Engineer",
    photo: "/students/antocreadev.png",
    bio: "Co-founder of Mindlet 🐙. Full stack developer with expertise in AI and Machine Learning. Passionate about Python, TypeScript, and modern web technologies.",
    age: 22,
    dateOfBirth: "2003-04-04",
    placeOfBirth: "Nice, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Python", "AI", "Machine Learning", "FastAPI", "JavaScript", "TypeScript", "React", "Next.js"],
    weaknesses: ["DevOps", "Kubernetes", "Docker"],
    biggestAchievement: "Co-founder of Mindlet 🐙",
    funFact: "Who runs, falls!",
  },
  {
    id: "achille-poirier",
    name: "Achille POIRIER",
    role: "Backend Developer",
    photo: "/students/achille.jpg",
    bio: "Backend specialist with strong CI/CD and Kubernetes skills. Created the webcomic platform at janov.eu/comic.",
    age: 22,
    dateOfBirth: "2003-01-06",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Backend", "CI/CD", "K8s"],
    weaknesses: ["CSS styling", "UI/UX design", "Presentation skills"],
    biggestAchievement: "Wrote the necessary code for running the webcomic at janov.eu/comic",
    funFact: "I really enjoy looking at pictures of pallas' cats",
  },
  {
    id: "vitalii-renkas",
    name: "Vitalii RENKAS",
    role: "Software Developer",
    photo: "/students/vitalii.png",
    bio: "Software developer with international perspective and strong technical foundation.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "Ukraine",
    nationality: "Ukrainian",
    flag: "🇺🇦",
    strengths: ["Programming Logic", "Adaptability", "Quick Learning"],
    weaknesses: ["French Language", "UI Design"],
    biggestAchievement: "Successfully adapted to studying in a foreign country while excelling in technical courses",
    funFact: "Speaks three languages fluently",
  },
  {
    id: "nicolas-robles",
    name: "Nicolas ROBLES",
    role: "Full Stack Developer",
    photo: "/students/nico.jpg",
    bio: "Full stack developer passionate about React, Node.js, and containerization. Created HealthyCore mobile app focused on fitness and nutrition.",
    age: 20,
    dateOfBirth: "2003-07-23",
    placeOfBirth: "Libourne, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["React", "Node.js", "PHP", "Kubernetes", "Docker", "Flask"],
    weaknesses: ["CSS", "TypeScript"],
    biggestAchievement: "Created a mobile app called HealthyCore, focused on fitness and nutrition",
    funFact: "Practice scuba diving and have earned several diving certifications",
  },
  {
    id: "stephane-thiry",
    name: "Stéphane THIRY",
    role: "Python Developer",
    photo: "/students/stephane.png",
    bio: "Python specialist focused on desktop application development with PyQt. Strong background in object-oriented programming and mobile development.",
    age: 27,
    dateOfBirth: "1998-04-08",
    placeOfBirth: "Ajaccio, France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Python object / PyQt", "Dev mobile", "Agile"],
    weaknesses: ["JS", "Web development"],
    biggestAchievement: "Made a desktop application with python and PyQt6",
    funFact: "I'm fun",
  },
// Data Engineers
  {
    id: "hafsa-abbouri",
    name: "Hafsa ABBOURI",
    role: "Data Engineer",
    photo: "/students/hafsa.jpeg",
    bio: "Data engineer passionate about building robust data pipelines and analytics solutions.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Processing", "ETL Pipelines", "Problem Solving"],
    weaknesses: ["Frontend Development", "UI Design"],
    biggestAchievement: "Built scalable data pipelines processing millions of records daily",
    funFact: "Can optimize SQL queries while drinking coffee",
  },
  {
    id: "mounia-bessam",
    name: "Mounia BESSAM",
    role: "Data Engineer",
    photo: "/students/mounia.png",
    bio: "Data engineer with a passion for transforming raw data into valuable insights.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Architecture", "Python", "SQL"],
    weaknesses: ["CSS", "Frontend Frameworks"],
    biggestAchievement: "Automated data processing workflows reducing manual work by 80%",
    funFact: "Enjoys solving complex data puzzles",
  },
  {
    id: "ambroise-kilimou",
    name: "Pouwedeou Ambroise KILIMOU",
    role: "Data Engineer",
    photo: "/students/ambroise.png",
    bio: "Data engineer with international perspective and strong analytical skills.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Integration", "API Development", "Analytical Thinking"],
    weaknesses: ["UI/UX", "Graphic Design"],
    biggestAchievement: "Integrated multiple data sources into a unified analytics platform",
    funFact: "Multilingual coder who thinks in different languages",
  },
  {
    id: "youssouf-maham",
    name: "Youssouf MAHAM BOWBA",
    role: "Data Engineer",
    photo: "/students/youssouf.png",
    bio: "Data engineer passionate about leveraging data for business decision-making.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Processing", "Spark", "Data Warehousing"],
    weaknesses: ["Frontend", "CSS Styling"],
    biggestAchievement: "Developed real-time data streaming solutions for business analytics",
    funFact: "Can debug data pipelines faster than most people can read them",
  },
  {
    id: "matthieu-michelozzi",
    name: "Matthieu MICHELOZZI",
    role: "Data Engineer",
    photo: "/students/matthieu.png",
    bio: "Experienced data engineer with expertise in building enterprise-level data solutions.",
    age: 23,
    dateOfBirth: "2002-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Architecture", "Cloud Platforms", "Performance Optimization"],
    weaknesses: ["Mobile Apps", "Game Development"],
    biggestAchievement: "Architected a scalable data platform handling petabytes of data",
    funFact: "Coffee-powered data wizard",
  },
  {
    id: "clementine-mirande",
    name: "Clémentine MIRANDE",
    role: "Data Engineer",
    photo: "/students/clementine.png",
    bio: "Data engineer combining technical skills with creative problem-solving approaches.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Data Pipelines", "Python", "Data Governance"],
    weaknesses: ["Low-level Programming", "Assembly"],
    biggestAchievement: "Implemented data governance framework ensuring compliance and quality",
    funFact: "Passionate about making data accessible to everyone",
  },
  {
    id: "abdou-seck",
    name: "Abdou Samath SECK",
    role: "Data Engineer",
    photo: "/students/abdou.png",
    bio: "Data engineer specializing in distributed systems and large-scale data processing.",
    age: 22,
    dateOfBirth: "2003-01-01",
    placeOfBirth: "France",
    nationality: "French",
    flag: "🇫🇷",
    strengths: ["Distributed Systems", "Data Processing", "Automation"],
    weaknesses: ["Frontend Development", "Design"],
    biggestAchievement: "Built high-performance data processing system handling millions of events",
    funFact: "Believes that good data architecture is like poetry",
  },
];

const mergedProfiles = newStudents.map(newStudent => {
  // Try to find existing profile to preserve extra data
  // Logic: Match by ID if possible, or somewhat fuzzy name match if needed?
  // It seems user provided IDs match what they want.
  
  // Note: Existing IDs in profiles.json were like "antocreadev", "medjourney", "dahdouh-ahmed"
  // New IDs are explicit. I'll check if any existing ID matches the new ID.
  
  const existing = existingProfiles.find(ep => ep.id === newStudent.id) || 
                   existingProfiles.find(ep => ep.name.toLowerCase() === newStudent.name.toLowerCase());

  let merged = {
    id: newStudent.id,
    name: newStudent.name,
    role: newStudent.role, // New field
    age: newStudent.age,
    date_of_birth: newStudent.dateOfBirth, // mapped
    place_of_birth: newStudent.placeOfBirth, // mapped
    nationality: newStudent.flag, // Using flag as nationality symbol
    nationality_text: newStudent.nationality, // New field
    image: newStudent.photo, // mapped
    bio: newStudent.bio, // New field from 'bio'
    coding_strengths: newStudent.strengths, // mapped
    coding_weaknesses: newStudent.weaknesses, // mapped
    biggest_achievement: newStudent.biggestAchievement, // mapped
    fun_fact: newStudent.funFact, // mapped
  };

  if (existing) {
    // Preserve rich fields if they exist
    if (existing.detailed_bio) merged.detailed_bio = existing.detailed_bio;
    if (existing.future_plans) merged.future_plans = existing.future_plans;
  }

  return merged;
});

console.log(`Merged ${mergedProfiles.length} profiles.`);
fs.writeFileSync(profilesPath, JSON.stringify(mergedProfiles, null, 2));
console.log('Saved to lib/profiles.json');
